export const allArtists = [
  
    {
      "fName": "Ashley",
      "lName": "Cai",
      "link": "acai",
      "artistDescription": "Ashley Cai is a designer, illustrator, storyteller, and Brown|RISD dual degree student from the San Francisco Bay Area. She is obsessed with becoming immersed in the emotions of other characters and hopes to deliver compelling and meaningful experiences. Her work often focuses on depicting narratives, characters, and fish; her animations have received critical acclaim from over a dozen film festivals and a silver medal from the Scholastic Art and Writing Awards. 1/3 of the profits from Ashley's work will go directly to charities focused on racial, economic, and environmental justice.",
    },
    {
        "fName": "Connie",
        "lName": "Gong",
        "link": "conniegong",
        "artistDescription": "Connie Gong (龚智璇) is a seventeen year old artist born in Atlanta, Georgia. She is currently based in Belmont, California, where she attends Carlmont High School. She has studied art under Yunhua Fang for the past ten years. \n \n Connie specializes in charcoal and printmaking, but has recently developed an interest in acrylic painting and graphic design as well. The deeply introspective nature of her art allows her to process the world around her. Creating work is therefore a means by which she can reach new understandings about herself and her environment as they relate to psychology, cultural identity, and emotion. \n \n Her work has been recognized by the Scholastic Art and Writing Awards, as well as her local and state PTA. Additionally, she has been published in The Daphne Review (2019), Navigating the Maze (2019), and the Stanford Anthology for Youth (2017). More of her work can be found on her website.",
    },
    {
      "fName": "Raymond",
      "lName": "Banke",
      "link": "raymondisdumb",
      "artistDescription": "hi i'm ray and i do dumb things",
    },
  ]
  
export const allArt = [

    {
      "artName": "Where the Wild Things Are",
      "artistName": "Angela Wei",
      "artImage": "",
      "link": "wildflower",
      "portrait": false,
      "artDescription": "‘Where the Wild Things Are’ is an exploration of color and linework. It features a figure kneeling in a forest of flowers that depicts a story that is simultaneously mundane yet also whimsical. Some stories that the artist was inspired by for this painting was Alice in Wonderland and the children’s story book, Where the Wild Things Are.",
      "artMedium": "acrylic",
    },
    {
      "artName": "Inferno",
      "artistName": "Angela Wei",
      "artImage": "",
      "link": "inferno",
      "portrait": false,
      "artDescription": "In an increasingly digitized age, we often are controlled by our technology. Our phones are becoming the entire way through which we perceive the world; many of us are no longer living in the moment but vicariously through others' feeds. ‘Inferno’ depicts the moment where one becomes powerless and possessed by technology. The main character falls into the abyss only to be scorched by her demons.",
      "artMedium": "acrylic",
    },
    {
      "artName": "In the Jungle (Ink Pen)",
      "artistName": "Angela Wei",
      "artImage": "",
      "link": "inthejungleink",
      "portrait": false,
      "artDescription": "One of Angela’s earlier works, ‘In the Jungle’ bears many similarities to her later works, namely ‘Where the Wild Things Are’, but is a much more stripped back, colorless, version. The piece draws upon mythological and oriental qualities, both of which are elements that the artist cites throughout her portfolio.",
      "artMedium": "inkpen",
    },
    {
      "artName": "In the Jungle (Color Pencil)",
      "artistName": "Angela Wei",
      "artImage": "",
      "link": "inthejunglecolorpencil",
      "portrait": true,
      "artDescription": "One of Angela’s earlier works, ‘In the Jungle’ bears many similarities to her later works, namely ‘Where the Wild Things Are’. The piece draws upon mythological and oriental qualities, both of which are elements that the artist cites throughout her portfolio. An original art piece that is identical to the black and white version but colored in by hand with color pencils. The use of traditional mediums in the piece gives it a greater fine art touch.",
      "artMedium": "colorpencil",
    },
    {
      "artName": "In the Jungle (Digital Cover)",
      "artistName": "Angela Wei",
      "artImage": "",
      "link": "inthejungledigital",
      "portrait": false,
      "artDescription": "One of Angela’s earlier works, ‘In the Jungle’ bears many similarities to her later works, namely ‘Where the Wild Things Are’. The piece draws upon mythological and oriental qualities, both of which are elements that the artist cites throughout her portfolio. Another version of the same series but rendered digitally. The digital coloring of this piece gives it more of a children’s storybook quality.",
      "artMedium": "digital",
    },
    {
      "artName": "Hook, Line, and Sinker",
      "artistName": "Ashley Cai",
      "artImage": "",
      "link": "hooklineandsinker",
      "portrait": false,
      "artDescription": "The vitality is drained out of the fish as they are suctioned through a robotic, merciless system. This triptych represents how capitalism values people only for their productivity and discards them once they are no longer of use.",
      "artMedium": "watercolor",
    },
    {
      "artName": "Banuga",
      "artistName": "Ashley Cai",
      "artImage": "",
      "link": "banuga",
      "portrait": false,
      "artDescription": "It's a banana beluga whale.",
      "artMedium": "digital",
    },
    {
      "artName": "Salmon Run / Salmon Ran",
      "artistName": "Ashley Cai",
      "artImage": "",
      "link": "salmonrunsalmonran",
      "portrait": true,
      "artDescription": "The annual trek salmon make back to their birthplace for mating season is an example of a beautiful, reckless persistence. Yet immediately after the salmon reach their destination and procreate, they begin to decay, and their corpses lay forgotten beneath new life.",
      "artMedium": "chalkpastel",
    },
    {
      "artName": "Please Remain Calm",
      "artistName": "Ashley Cai",
      "artImage": "",
      "link": "prcoriginal",
      "portrait": true,
      "artDescription": "A thin pane of glass is the only thing that separates her from the fiercely passionate mayhem that awaits outside. The cool tones and geometric shapes inside the apartment contrast against the saturated warmth and loose watercolors outside the window, representing inaction in the face of revolution.",
      "artMedium": "watercolor, inkpen",
    },
    {
      "artName": "Please Remain Calm",
      "artistName": "Ashley Cai",
      "artImage": "",
      "link": "prcprint",
      "portrait": false,
      "artDescription": "A thin pane of glass is the only thing that separates her from the fiercely passionate mayhem that awaits outside. The cool tones and geometric shapes inside the apartment contrast against the saturated warmth and loose watercolors outside the window, representing inaction in the face of revolution.",
      "artMedium": "watercolor, inkpen",
    },
]
