export const allArtists = [
  
    {
      "fName": "Ashley",
      "lName": "Cai",
      "link": "ashleycai",
      "artistDescription": "Ashley Cai is a designer, illustrator, storyteller, and Brown|RISD dual degree student from the San Francisco Bay Area. She is obsessed with becoming immersed in the emotions of other characters and hopes to deliver compelling and meaningful experiences. Her work often focuses on depicting narratives, characters, and fish; her animations have received critical acclaim from over a dozen film festivals and a silver medal from the Scholastic Art and Writing Awards. 1/3 of the profits from Ashley's work will go directly to charities focused on racial, economic, and environmental justice.",
    },
    {
        "fName": "Connie",
        "lName": "Gong",
        "link": "conniegong",
        "artistDescription": "Connie Gong (龚智璇) is a seventeen year old artist born in Atlanta, Georgia. She is currently based in Belmont, California, where she attends Carlmont High School. She has studied art under Yunhua Fang for the past ten years. \n \n Connie specializes in charcoal and printmaking, but has recently developed an interest in acrylic painting and graphic design as well. The deeply introspective nature of her art allows her to process the world around her. Creating work is therefore a means by which she can reach new understandings about herself and her environment as they relate to psychology, cultural identity, and emotion. Her work has been recognized by the Scholastic Art and Writing Awards, as well as her local and state PTA. Additionally, she has been published in The Daphne Review (2019), Navigating the Maze (2019), and the Stanford Anthology for Youth (2017). More of her work can be found on her website.",
    },
    {
      "fName": "Angela",
      "lName": "Wei",
      "link": "angelawei",
      "artistDescription": "Angela is a multidisciplinary artist majoring in Art History and Visual Arts at Barnard. Throughout her life, she has lived in multiple cities and studied at vastly different colleges, allowing her to develop a global and unique perspective while approaching her work. Her love for art and creativity began early; as a child, she entered into multiple painting competitions and won second place in North America at the United Nations Children Painting Competition and a Top Finalist in Canadian Portrait Society of Canada. In college, she really began to commit to her art more seriously and decided to move to New York to pursue her creative endeavors. Much of her art work’s style consists of highly illustrative narratives, painted with lively bold colors. Angela enjoys experimenting with incorporating different art styles, from traditional Chinese scroll paintings to Renaissance Portraiture. Because of the color palette, her work often alludes to a very bright and happy atmosphere, but upon closer inspection, offers more gruesome elements within. Feel free to connect with Angela over social media or check out her work at the links below. Insta: https://www.instagram.com/theangelawei/ Linkedin:https://www.linkedin.com/in/angela-wei-8180a7164/ Website: https://angelawei.cargo.site/",
    },
    {
      "fName": "Cynthia",
      "lName": "Zhou",
      "link": "cynthiazhou",
      "artistDescription": "Cynthia Zhou is a 18-year-old artist, designer, and poet currently attending studying design at the University of Pennsylvania. Her work -- which revolves around stories of equity and themes of memory + identity -- has been exhibited in the Kennedy Center in DC, as well as in NYC, San Francisco, Miami, and elsewhere. She is a 2018 National YoungArts Foundation Finalist and was recently recognized at the White House as a 2019 Presidential Scholar in the Arts. She loves amphibians, shiny stickers, and swing dancing. Hit her up at cynthiazhouart.com or @ethernautics on Instagram for cool lobster facts.",
    },
    {
      "fName": "Katrina",
      "lName": "Liou",
      "link": "katrinaliou",
      "artistDescription": "Katrina Liou is an artist and a student at Stanford University studying Product Design and Art Practice. Katrina’s work explores themes of imperfection, human anatomy and the human condition, often asking the question “What does it mean to be human?” Much of her work revolves around depicting the human body to explore the deeply hidden subtleties of the individual. In metaphoric imagery of human interaction, she searches for hints of character, personality, and hidden secrets to embed in the portrayal of flesh, folds of skin, wrinkles, and fat. Through this technique, she depicts the external elements as a display of internal emotion and personality. Examining the human condition through an anatomical lens allows her to engage in an interdisciplinary field that combines two seemingly disparate topics: art and science. At Stanford Katrina currently designs for Mint Magazine (Stanford’s culture and fashion magazine) and creates graphics for the Stanford Daily newspaper. Outside of school she also designs graphics of Hearts Over Hands, a volunteer organization that provides COVID-19 relief for families with young children. More of her work can be found on Instagram @knips00 or online at https://katrinaliou.squarespace.com.",
    },
    {
      "fName": "Liza",
      "lName": "Evseeva",
      "link": "lizaevseeva",
      "artistDescription": "Liza Evseeva is a 2nd year Columbia University student. She hails from the suburbs of DC and originally, from Moscow, Russia. She's a staff illustrator at the Columbia Daily Spectator and a freelance artist and photographer. She believes in constantly pushing one’s comfort zone and experimenting. After 10 years of formal art courses, Liza has a wide range of skills in various traditional and digital mediums and techniques. She can execute still lives, landscapes, portraits, or some combination of those. Her preferred mediums are digital painting and acrylic and oil paint. Liza enjoys working with bold colors, rough textures, and weaving characters into their environments. In her personal artwork, she likes capturing emotion through color and lighting and conveying concepts through surrealist artwork.You can find more info on Liza’s website at newelizzia.wixsite.com/website, or follow her on Instagram @liza.e.art.",
    },
    {
      "fName": "Tao",
      "lName": "Liu",
      "link": "taoliu",
      "artistDescription": "Tao Liu is a 20-year-old Chinese born artist based in New York City and Kunming, China. Inspired by personal life experiences, Liu expresses his understanding of self and the world around him through a series of visual metaphors. His work also deals with the cultural clash between the East and the west. The medium of his work varies from charcoal drawing and oil painting to installation and performance. He has received a number of awards from the Scholastic Arts and Writing Awards, including 8 Gold Keys, 4 Silver Keys, 4 National Gold Metals and American Vision Award. His work The “Praying” Hands was selected into the Art.Write.Now. traveling exhibition in galleries across 4 cities. He was also an American YoungArts Award winner in 2019. He currently studies integrated design at  Parsons School of Design at The New School in New York City. For more information about Liu, please visit his Instagram: the_world_tao_sees, or check out his website: theworldtaosees.com",
    },
    {
      "fName": "Rick",
      "lName": "Zhang",
      "link": "rickzhang",
      "artistDescription": "",
    }
  ]
  
export const allArt = [

    {
      "artName": "Hook, Line, and Sinker",
      "artistName": "Ashley Cai",
      "artImage": "hooklinesinker",
      "link": "hooklinesinker",
      "portrait": false,
      "artDescription": "The vitality is drained out of the fish as they are suctioned through a robotic, merciless system. This triptych represents how capitalism values people only for their productivity and discards them once they are no longer of use.",
      "artMedium": "watercolor",
    },
    {
      "artName": "Banuga",
      "artistName": "Ashley Cai",
      "artImage": "banuga",
      "link": "banuga",
      "portrait": false,
      "artDescription": "It's a banana beluga whale.",
      "artMedium": "digital",
    },
    {
      "artName": "Please Remain Calm",
      "artistName": "Ashley Cai",
      "artImage": "pleaseremaincalm",
      "link": "pleaseremaincalm",
      "portrait": false,
      "artDescription": "A thin pane of glass is the only thing that separates her from the fiercely passionate mayhem that awaits outside. The cool tones and geometric shapes inside the apartment contrast against the saturated warmth and loose watercolors outside the window, representing inaction in the face of revolution.",
      "artMedium": "watercolor, inkpen", 
    },
    {
      "artName": "Where the Wild Things Are",
      "artistName": "Angela Wei", 
      "artImage": "wherethewildthingsare",
      "link": "wherethewildthingsare",
      "portrait": false,
      "artDescription": "‘Where the Wild Things Are’ is an exploration of color and linework. It features a figure kneeling in a forest of flowers that depicts a story that is simultaneously mundane yet also whimsical. Some stories that the artist was inspired by for this painting was Alice in Wonderland and the children’s story book, Where the Wild Things Are.",
      "artMedium": "acrylic",
    },
    {
      "artName": "Inferno",
      "artistName": "Angela Wei", 
      "artImage": "inferno",
      "link": "inferno",
      "portrait": false,
      "artDescription": "In an increasingly digitized age, we often are controlled by our technology. Our phones are becoming the entire way through which we perceive the world; many of us are no longer living in the moment but vicariously through others' feeds. ‘Inferno’ depicts the moment where one becomes powerless and possessed by technology. The main character falls into the abyss only to be scorched by her demons.",
      "artMedium": "acrylic",
    },
    {
      "artName": "In the Jungle (Digital Color)",
      "artistName": "Angela Wei", 
      "artImage": "inthejungledigital",
      "link": "inthejungledigital",
      "portrait": false,
      "artDescription": "One of Angela’s earlier works, ‘In the Jungle’ bears many similarities to her later works, namely ‘Where the Wild Things Are’, but is a much more stripped back, colorless, version. The piece draws upon mythological and oriental qualities, both of which are elements that the artist cites throughout her portfolio. The digital coloring of this piece gives it more of a children’s storybook quality.",
      "artMedium": "digital",
    },
    {
      "artName": "In the Jungle (Ink Pen)",
      "artistName": "Angela Wei", 
      "artImage": "inthejungleinkpen",
      "link": "inthejungleinkpen",
      "portrait": false,
      "artDescription": "One of Angela’s earlier works, ‘In the Jungle’ bears many similarities to her later works, namely ‘Where the Wild Things Are’, but is a much more stripped back, colorless, version. The piece draws upon mythological and oriental qualities, both of which are elements that the artist cites throughout her portfolio. An original art piece that is identical to the black and white version but colored in by hand with color pencils. The use of traditional mediums in the piece gives it a greater fine art touch.",
      "artMedium": "inkpen",
    },
    {
      "artName": "In the Jungle (Color Pencil)",
      "artistName": "Angela Wei", 
      "artImage": "inthejunglecp",
      "link": "inthejunglecp",
      "portrait": true,
      "artDescription": "One of Angela’s earlier works, ‘In the Jungle’ bears many similarities to her later works, namely ‘Where the Wild Things Are’, but is a much more stripped back, colorless, version. The piece draws upon mythological and oriental qualities, both of which are elements that the artist cites throughout her portfolio. The piece draws upon mythological and oriental qualities, both of which are elements that the artist cites throughout her portfolio.",
      "artMedium": "colorpencil",
    },
    {
      "artName": "Eden",
      "artistName": "Connie Gong",
      "artImage": "eden",
      "link": "eden",
      "portrait": true,
      "artDescription": "After seeing the German Art After 1960 exhibition at the San Francisco Museum of Modern Art, Connie was inspired by the artists' use of texture and sought to explore the materiality of flexible modeling paste through a series of paintings. Among those paintings is Eden, whose title is a reference to the biblical paradise. The work depicts a pond of water lilies among a lush forest and is notable for the presence of soft light throughout the composition.",
      "artMedium": "acrylic",
    },
    {
      "artName": "Passage of Time",
      "artistName": "Connie Gong",
      "artImage": "passageoftime",
      "link": "passageoftime",
      "portrait": false,
      "artDescription": "Passage of Time originated as a single acrylic painting that explored the sensation of time. After finishing the individual piece, Connie wanted to further explore this sensation and hence, two more pieces were created to form a set of three paintings. Collectively, the triptych highlights Connie’s belief that an awareness of time only increases throughout a lifetime. As the viewer's eye travels from left to right, they follow this awareness as it begins in childhood with vague acknowledgement and transforms in late adulthood as an unrelenting reminder that although time is infinite, each individual's time in this life is not.",
      "artMedium": "acrylic",
    },
    {
      "artName": "I Dreamt We Spoke Again",
      "artistName": "Cynthia Zhou",
      "artImage": "idreamtwespokeagain",
      "link": "idreamtwespokeagain",
      "portrait": true,
      "artDescription": "I Dreamt We Spoke Again is a 2D cardboard sculpture detailing the “two-headedness” of remembering, the bittersweet attempt to wish something into existence again. In this piece, colorful, docile hands are juxtaposed with a black and white snake. One head hesitates and recedes back into the hands, while the other head reaches upwards.",
      "artMedium": "oil",
    },
    {
      "artName": "An Affinity for Dreaming",
      "artistName": "Cynthia Zhou",
      "artImage": "affinityfordreamingHQ",
      "link": "affinityfordreamingHQ",
      "portrait": true,
      "artDescription": "An Affinity for Dreaming is a portrait of the artist’s younger brother. In this piece, multiple faces echo the restlessness of living in perpetual stalemate, torn between the powerful compulsion to boldly go forth and the equally powerful apprehension of failure. The presence of fluorescent pink peeking through layers of greys and blues, however, suggests that underneath self doubt lies the enduring existence of conviction.",
      "artMedium": "oil",
    },
    {
      "artName": "PINK",
      "artistName": "Cynthia Zhou",
      "artImage": "pinkHQ",
      "link": "pinkHQ",
      "portrait": false,
      "artDescription": "Because of its stigmatization as the “gay disease”, tens of thousands of Americans would die before any substantial action was taken from the Reagan administration. Politicizing an apolitical virus meant that the queer community of the 1980’s was all but wiped out. This is a portrait of every queer person who lived and died anonymously in the AIDS era; faceless but not forgotten. As COVID-19 continues to surge in 2020, the same historical patterns are reinstated—disease becomes a partisan issue, and ethnic and racial minorities are disproportionately affected by the virus.",
      "artMedium": "oil",
    },
    {
      "artName": "Domesticate",
      "artistName": "Cynthia Zhou",
      "artImage": "boxers",
      "link": "boxers",
      "portrait": true,
      "artDescription": "What does it mean to domesticate violence? In this piece, the viewer becomes a voyeur to a nonsensical fight scene in the snow. From the boxers’ stitched faces hang tickets to future fights. The artist questions the ways we have repackaged and reinvented the cyclical nature of violence, designating it spaces within the home, the screen, and positions of power–and argues that normalizing violence desensitizes those who observe it.",
      "artMedium": "oil",
    },
    {
      "artName": "Baozi Jiaozi",
      "artistName": "Katrina Liou",
      "artImage": "baozijiaozi",
      "link": "baozijiaozi",
      "portrait": true,
      "artDescription": "The “Baozi Jiaozi” piece was designed for a hypothetical Chinese menu for a project at the California State Summer School for the Arts.",
      "artMedium": "gouache",
    },
    {
      "artName": "The Good Old Days",
      "artistName": "Katrina Liou",
      "artImage": "thegoodolddays",
      "link": "thegoodolddays",
      "portrait": true,
      "artDescription": "",
      "artMedium": "acrylic",
    },
    {
      "artName": "Falling",
      "artistName": "Katrina Liou",
      "artImage": "falling",
      "link": "falling",
      "portrait": false,
      "artDescription": "“Falling” examines human relationships and interaction during turbulent experiences. Stylized line quality evokes rawness and invites viewers to question emotion.",
      "artMedium": "acrylic, sumi ink",
    },
    {
      "artName": "Traversing Time",
      "artistName": "Katrina Liou",
      "artImage": "traversingtime",
      "link": "traversingtime",
      "portrait": true,
      "artDescription": "“Traversing Time” explores the role time and space plays in the formation of human connection.",
      "artMedium": "color pencil, charcoal",
    },
    {
      "artName": "Tangled",
      "artistName": "Katrina Liou",
      "artImage": "tangled",
      "link": "tangled",
      "portrait": false,
      "artDescription": "“Tangled” examines interconnectedness.",
      "artMedium": "acrylic, sumi ink",
    },
    {
      "artName": "Portrait Study",
      "artistName": "Katrina Liou",
      "artImage": "portraitstudy",
      "link": "portraitstudy",
      "portrait": false,
      "artDescription": "",
      "artMedium": "digital",
    },
    {
      "artName": "Black Hole",
      "artistName": "Katrina Liou",
      "artImage": "blackhole",
      "link": "blackhole",
      "portrait": true,
      "artDescription": "",
      "artMedium": "acrylic, newspaper",
    },
    {
      "artName": "Goldfish",
      "artistName": "Katrina Liou",
      "artImage": "goldfishbowl",
      "link": "goldfishbowl",
      "portrait": true,
      "artDescription": "",
      "artMedium": "watercolor"
    },
    {
      "artName": "Sun Room",
      "artistName": "Liza Evseeva",
      "artImage": "sunroom",
      "link": "sunroom",
      "portrait": false,
      "artDescription": "Liza originally developed the concept for this piece in 2018, as part of her 12-piece final concentration for her high school AP 2D Design (digital art) course. Liza's concentration explored the various worlds connected by windows. She used a saturated, painterly style that romanticizes reality, along with a limited color scheme for each piece to set a mood that ties together the subjects on both sides of the glass. For this piece, Liza wanted to create a warm, inviting mood, with the windows playing a large part in setting the scene. 'This is my dream room,' she says.",
      "artMedium": "digital"
    },
    {
      "artName": "Reaching",
      "artistName": "Liza Evseeva",
      "artImage": "reaching",
      "link": "reaching",
      "portrait": true,
      "artDescription": "Reaching is a prime example of Liza's experimentation with traditional mediums. Due to the see-through background, the piece can be re-contextualized when placed in different settings. The motion of the hands signifies both reaching towards a goal, and holding yourself back due to doubt. This is also reflected in the transition from cool colors in the bottom of the painting, to warm tones in the top fingertips. This painting is mysterious, tense, yet still hopeful.",
      "artMedium": "acrylic, glass",
    },
    {
      "artName": "RGB",
      "artistName": "Liza Evseeva",
      "artImage": "rgb",
      "link": "rgb",
      "portrait": true,
      "artDescription": "Liza does a lot of digital painting, and in this piece, she intended to bring the clean, vibrant, 'digital' quality to a traditional portrait. Even though she used a photo by Petra Collins as a reference, she made the portrait her own by painting it semi-realistically -- exaggerating the colors, simplifying features, and using expressive brush strokes. Liza loves working with vibrant colors, and the colorful lighting in this piece certainly shows that.",
      "artMedium": "acrylic, oil",
    },
    {
      "artName": "Big Blue",
      "artistName": "Liza Evseeva",
      "artImage": "bigblue",
      "link": "bigblue",
      "portrait": false,
      "artDescription": "Liza originally developed the concept for this piece in 2018, as part of her 12-piece final concentration for her high school AP 2D Design (digital art) course. Liza's concentration explored the various worlds connected by windows. She used a saturated, painterly style that romanticizes reality, along with a limited color scheme for each piece to set a mood that ties together the subjects on both sides of the glass. In Big Blue, Liza predominantly used blue to convey the grandeur and calm of the whale. However, she added a tinge of reddish-orange to the silhouette of the boy to not only complete the complementary color scheme, but also to show the excitement the child is feeling.",
      "artMedium": "digital"
    },
    
  
  
]
